# Copyright (c) 2026 Peter Huang.
# SPDX-License-Identifier: BSD-3-Clause

"""Internal native boundary for the UniRT Python package."""

from ._api import (
    UniRTError,
    _check,
    _encode,
    _str_list_to_c,
    deinit,
    ensure_init,
    get_compute_unit_list,
    get_plugin_version,
    get_runtime_list,
    init,
    resolve_device,
    set_log_level,
    version,
)
from ._lib import load_library
from ._types import (
    unirt_EmbeddingCreateInput,
    unirt_EmbeddingEncodeInput,
    unirt_EmbeddingEncodeOutput,
    unirt_EmbeddingRuntimeStats,
    unirt_GenerationConfig,
    unirt_GetDeviceListInput,
    unirt_GetDeviceListOutput,
    unirt_GetPluginListOutput,
    unirt_KvCacheLoadInput,
    unirt_KvCacheLoadOutput,
    unirt_KvCacheSaveInput,
    unirt_KvCacheSaveOutput,
    unirt_LlmApplyChatTemplateInput,
    unirt_LlmApplyChatTemplateOutput,
    unirt_LlmChatMessage,
    unirt_LlmCreateInput,
    unirt_LlmGenerateInput,
    unirt_LlmGenerateOutput,
    unirt_LlmModelInfo,
    unirt_LlmRuntimeStats,
    unirt_ModelConfig,
    unirt_ProfileData,
    unirt_ResolveDeviceInput,
    unirt_ResolveDeviceOutput,
    unirt_SamplerConfig,
    unirt_VlmApplyChatTemplateInput,
    unirt_VlmApplyChatTemplateOutput,
    unirt_VlmCapabilities,
    unirt_VlmChatMessage,
    unirt_VlmContent,
    unirt_VlmCreateInput,
    unirt_VlmGenerateInput,
    unirt_VlmGenerateOutput,
    unirt_token_callback,
)

__all__ = [
    'UniRTError',
    '_check',
    '_encode',
    '_str_list_to_c',
    'deinit',
    'ensure_init',
    'get_compute_unit_list',
    'get_plugin_version',
    'get_runtime_list',
    'init',
    'load_library',
    'resolve_device',
    'set_log_level',
    'version',
    'unirt_EmbeddingCreateInput',
    'unirt_EmbeddingEncodeInput',
    'unirt_EmbeddingEncodeOutput',
    'unirt_EmbeddingRuntimeStats',
    'unirt_GenerationConfig',
    'unirt_GetDeviceListInput',
    'unirt_GetDeviceListOutput',
    'unirt_GetPluginListOutput',
    'unirt_KvCacheLoadInput',
    'unirt_KvCacheLoadOutput',
    'unirt_KvCacheSaveInput',
    'unirt_KvCacheSaveOutput',
    'unirt_LlmApplyChatTemplateInput',
    'unirt_LlmApplyChatTemplateOutput',
    'unirt_LlmChatMessage',
    'unirt_LlmCreateInput',
    'unirt_LlmGenerateInput',
    'unirt_LlmGenerateOutput',
    'unirt_LlmModelInfo',
    'unirt_LlmRuntimeStats',
    'unirt_ModelConfig',
    'unirt_ProfileData',
    'unirt_ResolveDeviceInput',
    'unirt_ResolveDeviceOutput',
    'unirt_SamplerConfig',
    'unirt_VlmApplyChatTemplateInput',
    'unirt_VlmApplyChatTemplateOutput',
    'unirt_VlmCapabilities',
    'unirt_VlmChatMessage',
    'unirt_VlmContent',
    'unirt_VlmCreateInput',
    'unirt_VlmGenerateInput',
    'unirt_VlmGenerateOutput',
    'unirt_token_callback',
]
